### PR TITLE
Various items

### PR DESCRIPTION
**Pull request by Nerillida**
Hallow's End under HW
War Effort under Hy
many NPCs/items/objects.

Quest stuff to follow if you accept this.
Please let me know if there are problems.

Regarding Holidays etc. However you eventually are able to detect/fral with holidays, there are quite a lot of them.
In the short term, could you hide the Hy ones, or maybe add the holiday.
Regarding the Commendation Officers visible around the cities. The conditions, the P: s are probably wrong as they should only appear after the War Effort. However, it probably does no harm to leave them for now.

Thanks

### CODE REVIEW

**Comment by smaitch** [comment]
Can you resolve the conflicts?

**Comment by Nerillida** [comment]
The Resolve Conflicts button is disabled. Can't work out what to do at this stage. Do you reject it and I have to go over it again?

**Comment by Nerillida** [comment]
Read some advice regarding conflict resolution.
It seminally requires me to learn some command line tool usage. Hmm.
Not sure what's wrong here. I can't see errors. Is there too much data for the web based software to handle?
I have no idea where to go from here, it's new territory for me.

**Comment by smaitch** [comment]
OK, I will take a look at it later this evening.  I will see about resolving the conflicts.

**Pull request merged**
