### PR TITLE
Classic - running updates

### PR DESCRIPTION
**Pull request by Nerillida**
Add race to "downstream" flying quest chains so that they show the correct info.
2790 - thinning comment
2083 - format
Additional class specificity 1880
Additional race specificity, 6388, 6391, 6392.

### CODE REVIEW

**Comment by smaitch** [comment]
Just to let you know that "inherited" race requirements that are not marked by Blizzard explicitly will be erased with the next automatic quest processing.  For example, if a prerequisite quest has RU, quests that require may not be marked with RU, so manually marking them will be overwritten.  Non-RU will still not be able to get the quest because it will be marked as unobtainable because of "inherited" race.

**Comment by Nerillida** [comment]
OK, yes you can delete them if you want.
It was a friend wondering about these quests that prompted me. It's not obvious in the log, the inheritance of the racial aspect, just says Race Any for the downstream quests. 
Hopefullythe class quest change will stick.

**Comment by smaitch** [comment]
Class requirements are not provided by Blizzard that I know, so we manually maintain those.

It might be possible to make Wholly show the inherited reasons, but it will take some work.  Grail only tells that it is a reason, but not the specific race.

**Comment by Nerillida** [comment]
Fine, if you want me to revert those changes, please say so. Or maybe let them go through and let them revert when you do your updates from your source.

**Comment by Nerillida** [comment]
Any reason not in latest?

**Pull request merged**
