### PR TITLE
Shadowlands

### PR DESCRIPTION
**Pull request by yoshimo**
The first few quests in the maw, a bit rough due to bugs and my inability to automatically convert NPC data.

### CODE REVIEW

**Comment by yoshimo** [comment]
Adds a couple of Build infos and connections between quests.

**Comment by yoshimo** [comment]
@smaitch will you rebase it or should i?

**Comment by smaitch** [comment]
I think you should handle the rebase.

**Comment by yoshimo** [comment]
Wondering if it makes sense to parse both wowhead and wowdb beta dbs and take the lowest build for each quest automatically and add it to the db. Maybe just a nit for a completionist like me.

**Comment by yoshimo** [comment]
@smaitch if you constantly push your changes before mine the rebasing game will never stop ;)

**Pull request merged**
