### PR TITLE
split DB into one file per each expansion #308

### PR DESCRIPTION
**Pull request by yoshimo**
This is a draft to get the discussion of #308 going.
I am aware that it is not a consistent naming scheme but before the DF prepatch drops we should get this done or at least started
@smaitch

### CODE REVIEW

**Comment by smaitch** [comment]
I don't think we need one for TBC.  It appears that is no longer a possibility...only Wrath and plain classic.  Is that not true?

**Comment by yoshimo** [comment]
I wanted to keep it consistent. So we can compare with other projects that made the distinction like Questie or Zygor later on. 
Maybe a SeasonOfMastery will happen. We never know

**Comment by Wyr3d** [comment]
If you are planning on making Wholly and Grail available for private TBC servers, then you might want to keep a TBC version, yeah. Since Blizzard have no plan (at this time) to create a TBC Legacy server, it's only a matter of time before private TBC servers get popular again - at which point Blizzard may change their mind about TBC Legacy servers.

**Comment by yoshimo** [comment]
@smaitch could we do this & #318 before df changes make this too hard

**Pull request closed without merging**
